name: build ci docker images

on:
  push:
    # Build on any branch when docker files change
    paths:
      - 'docker/ci/**'
  workflow_dispatch: # manual trigger option

jobs:
  build-centos7:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Determine branch name
      - name: Set branch environment variables
        id: branch_env
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "is_master=${{ github.ref == 'refs/heads/master' }}" >> $GITHUB_OUTPUT
          
      - name: build and push centos 7.9.2009 image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/ci/centos7.9.2009
          push: true
          tags: |
            ${{ steps.branch_env.outputs.is_master == 'true' && format('ghcr.io/{0}/fig-ci:centos7.9.2009', github.repository) || '' }}
            ghcr.io/${{ github.repository }}/fig-ci:centos7.9.2009-${{ steps.branch_env.outputs.branch_name }}
