name: build ci docker images

on:
  push:
    branches: [ master ]
    paths:
      - 'docker/ci/**'
  workflow_dispatch: # manual trigger option

jobs:
  build-centos7:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build and push centos 7.9.2009 image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/ci/centos7.9.2009
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fig-ci:centos7.9.2009
            ghcr.io/${{ github.repository }}/fig-ci:centos7.9.2009-${{ github.sha }}
