name: tebako

on:
  push:
  workflow_dispatch:

# Ensure we don't run duplicate workflows
concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: true

env:
  BUNDLER_VER: 2.6.1
  RUBYGEMS_VER: 3.6.1

jobs:
  # Package the gem into platform-specific executables using tebako
  tebako-package-linux:
    runs-on: ubuntu-latest
    
    env:
      artifact: "fig-linux-amd64"

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler: '2.6.1'
          rubygems: '3.6.1'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install --no-cache
        
      - name: Build gem
        run: bundler exec rake build
        
      # Run tebako in docker (Linux)
      - name: Create executable with tebako (Linux)
        env:
          image_name: ${{ matrix.docker_image }}
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -w /workspace \
            ghcr.io/tamatebako/tebako-ubuntu-20.04:latest \
            tebako press \
              --patchelf \
              --root=pkg \
              --entry-point=fig \
              --output=${{ env.artifact }}

      # Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}
          retention-days: 30

  tebako-package-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS AMD64
          - os: macos-14
            platform: macos
            artifact: fig-macos-amd64
            use_docker: false
          # macOS ARM64
          - os: macos-14
            platform: macos
            artifact: fig-macos-arm64
            use_docker: false
            env:
              ARCHFLAGS: "-arch arm64"
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler: '2.6.1'
          rubygems: '3.6.1'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install --no-cache
        
      - name: Build gem
        run: bundler exec rake build
        
      # Set up tebako for non-Linux platforms
      - name: Setup tebako
        uses: tamatebako/tebako/.github/actions/setup-tebako@main
        with:
          ruby_version: '3.3.4'

      # Run tebako directly (non-Linux)
      - name: Create executable with tebako
        run: |
          tebako press \
            --root=pkg \
            --entry-point=fig \
            --output=${{ matrix.artifact }}

      # Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
          retention-days: 30

  tebako-package-windows:
    runs-on: windows-2022

    env:
      artifact: "fig-windows-amd64.exe"
      sys: "ucrt64"
      CC: "gcc"
      CXX: "g++"
      
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
      - name: Setup MSys
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          path-type: minimal
          update: true
          install: >-
            git
            tar
            bison
            flex
          pacboy: >-
            cmake:p
            boost:p
            diffutils:p
            libevent:p
            double-conversion:p
            fmt:p
            glog:p
            dlfcn:p
            ninja:p
            gtest:p
            autotools:p
            ncurses:p
            toolchain:p
            openssl:p
            make:p
            libyaml:p
            libxslt:p

      # Set up tebako for non-Linux platforms
      - name: Setup tebako
        run: |
          gem install tebako
                    
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler: '2.6.1'
          rubygems: '3.6.1'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install --no-cache
        
      - name: Build gem
        run: bundler exec rake build
        
      # Run tebako directly (non-Linux)
      - name: Create executable with tebako
        run: |
          tebako press --root=pkg --entry-point=fig --output=${{ env.artifact }}

      # Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact }}
          path: ${{ env.artifact }}
          retention-days: 30

  smoke-test-linux:
    needs: tebako-package-linux
    runs-on: ubuntu-latest

    container: ${{ matrix.target_os }}

    strategy:
      fail-fast: false
      matrix:
        target_os:
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - rockylinux:9.3
        executable: [ fig-linux-amd64 ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.executable }}
          path: ./

      - name: Ensure executable
        run: chmod +x ./${{ matrix.executable }}

      - name: version check
        run: ./${{ matrix.executable }} --version

      - name: help
        run: ./${{ matrix.executable }} --help

      - name: Hello World
        run: ./${{ matrix.executable }} -s GREETING=Hello -- 'echo $GREETING, World'

  smoke-test-not-linux:
    needs: [ tebako-package-macos, tebako-package-windows]
    runs-on: ${{ matrix.target_os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target_os: macos-14
            executable: fig-macos-amd64
          - target_os: macos-14
            executable: fig-macos-arm64
          - target_os: macos-15
            executable: fig-macos-amd64
          - target_os: macos-15
            executable: fig-macos-arm64
          - target_os: windows-2022
            executable: fig-windows-amd64.exe

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.executable }}
          path: ./

      - name: Ensure executable
        if: ${{ ! startsWith( matrix.target_os, 'windows') }}
        run: chmod +x ./${{ matrix.executable }}

      - name: version check
        run: ./${{ matrix.executable }} --version

      - name: help
        run: ./${{ matrix.executable }} --help

      - name: Hello World
        run: ./${{ matrix.executable }} -s GREETING=Hello -- 'echo $GREETING, World'

